### ISSUE TITLE
Importing macros: maybe mention magic-compiler-internal std macros?

### ISSUE THREAD

**Issue by LukasKalbertodt** [rust-lang/edition-guide#154]
I was a bit confused by the chapter about macro imports. See [this StackOverflow question](https://stackoverflow.com/q/55444086/2408867). In short: there are some macros in `std` that cannot be imported via `use`. Maybe this should be mentioned? Right now it sounds like I can import all macros from extern crates via `use`.

And/or: maybe this is a bug and it should be possible to import the macros via `use`, too?

**Comment by steveklabnik** [comment]
I *think* this is a bug, but I’m not sure.

**Comment by LukasKalbertodt** [comment]
@steveklabnik Might very well be! @Shepmaster found [this thread](https://github.com/rust-lang/rust/issues/56417) where it's briefly mentioned.

**Comment by ehuss** [comment]
In #232 this section has moved to https://github.com/rust-lang/edition-guide/blob/302a115e8f71876dfc884aebb0ca5ccb02b8a962/src/rust-2018/path-changes.md#macros.  

I have been working on name resolution documentation for the reference, and hopefully the [`use` chapter](https://doc.rust-lang.org/reference/items/use-declarations.html) will get updated with all sorts of goodness.  And I believe since this has been written, many macros have become less magic and more "normal".

**Comment by ehuss** [comment]
I believe this is now resolved via https://github.com/rust-lang/rust/pull/62086 (built-in macros can now be imported).
