### ISSUE TITLE
Spelling mistake?

### ISSUE THREAD

**Issue by N4tus** [rust-lang/edition-guide#260]
There seems to be a small spelling mistake in https://github.com/rust-lang/edition-guide/blob/master/src/rust-2021/or-patterns-macro-rules.md.  
In the section 'Migration to Rust 2021'  `$:_pat` should probably be `$_:pat`.

**Comment by AaronErhardt** [comment]
Since this is a spelling mistake as well I'll add another one here in the comments: 
In [https://github.com/rust-lang/edition-guide/blob/master/src/rust-2021/IntoIterator-for-arrays.md](https://github.com/rust-lang/edition-guide/blob/master/src/rust-2021/IntoIterator-for-arrays.md) in the last point of the summary it says `IntoIterator::into_inter` instead of `IntoIterator::into_iter` as u/76g2maesu8mk2 pointed out on reddit.
